"""The name of every rule a fault of kb's own carries, which kb publishes (adrs/0018)."""

NOT_FOUND = "not-found"
KIND = "kind"
LOCATOR = "locator"
COLLECTION = "collection"
IDENTITY = "identity"
ON_DELETE = "on_delete"
UNREADABLE = "unreadable"
ITEM_NAME = "item-name"
SHAPE = "shape"
BUILT_ON = "built-on"
TARGETS = "targets"
VERSION = "version"
CONTENT = "content"
SECTIONS = "sections"
REF = "ref"
ACTOR = "actor"
MESSAGE = "message"
OPERATIONS = "operations"
SINCE = "since"
TITLE = "title"
ROOT = "root"
STORE = "store"
CLOCK = "clock"

ALL = tuple(value for name, value in sorted(globals().items()) if name.isupper() and name != "ALL")
