# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kb.contract import kb_pb2 as kb_dot_contract_dot_kb__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kb/contract/kb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KbStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/kb.v1.Kb/Init',
                request_serializer=kb_dot_contract_dot_kb__pb2.InitRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/kb.v1.Kb/Create',
                request_serializer=kb_dot_contract_dot_kb__pb2.CreateRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/kb.v1.Kb/Read',
                request_serializer=kb_dot_contract_dot_kb__pb2.ReadRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/kb.v1.Kb/Validate',
                request_serializer=kb_dot_contract_dot_kb__pb2.ValidateRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Replace = channel.unary_unary(
                '/kb.v1.Kb/Replace',
                request_serializer=kb_dot_contract_dot_kb__pb2.ReplaceRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.ReplaceResponse.FromString,
                _registered_method=True)
        self.Journal = channel.unary_unary(
                '/kb.v1.Kb/Journal',
                request_serializer=kb_dot_contract_dot_kb__pb2.JournalRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.JournalResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/kb.v1.Kb/Search',
                request_serializer=kb_dot_contract_dot_kb__pb2.SearchRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Refs = channel.unary_unary(
                '/kb.v1.Kb/Refs',
                request_serializer=kb_dot_contract_dot_kb__pb2.RefsRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.RefsResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/kb.v1.Kb/List',
                request_serializer=kb_dot_contract_dot_kb__pb2.ListRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/kb.v1.Kb/Snapshot',
                request_serializer=kb_dot_contract_dot_kb__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.Add = channel.unary_unary(
                '/kb.v1.Kb/Add',
                request_serializer=kb_dot_contract_dot_kb__pb2.AddRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/kb.v1.Kb/Remove',
                request_serializer=kb_dot_contract_dot_kb__pb2.RemoveRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.RemoveResponse.FromString,
                _registered_method=True)
        self.CreateMany = channel.unary_unary(
                '/kb.v1.Kb/CreateMany',
                request_serializer=kb_dot_contract_dot_kb__pb2.CreateManyRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.CreateManyResponse.FromString,
                _registered_method=True)
        self.ReplaceMany = channel.unary_unary(
                '/kb.v1.Kb/ReplaceMany',
                request_serializer=kb_dot_contract_dot_kb__pb2.ReplaceManyRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.ReplaceManyResponse.FromString,
                _registered_method=True)
        self.AddMany = channel.unary_unary(
                '/kb.v1.Kb/AddMany',
                request_serializer=kb_dot_contract_dot_kb__pb2.AddManyRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.AddManyResponse.FromString,
                _registered_method=True)
        self.RemoveMany = channel.unary_unary(
                '/kb.v1.Kb/RemoveMany',
                request_serializer=kb_dot_contract_dot_kb__pb2.RemoveManyRequest.SerializeToString,
                response_deserializer=kb_dot_contract_dot_kb__pb2.RemoveManyResponse.FromString,
                _registered_method=True)


class KbServicer:
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Journal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.InitRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.InitResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.CreateRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.CreateResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.ReadRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.ReadResponse.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.ValidateRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.ValidateResponse.SerializeToString,
            ),
            'Replace': grpc.unary_unary_rpc_method_handler(
                    servicer.Replace,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.ReplaceRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.ReplaceResponse.SerializeToString,
            ),
            'Journal': grpc.unary_unary_rpc_method_handler(
                    servicer.Journal,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.JournalRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.JournalResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.SearchRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.SearchResponse.SerializeToString,
            ),
            'Refs': grpc.unary_unary_rpc_method_handler(
                    servicer.Refs,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.RefsRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.RefsResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.ListRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.ListResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.SnapshotRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.SnapshotResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.AddRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.AddResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.RemoveRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.RemoveResponse.SerializeToString,
            ),
            'CreateMany': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMany,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.CreateManyRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.CreateManyResponse.SerializeToString,
            ),
            'ReplaceMany': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceMany,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.ReplaceManyRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.ReplaceManyResponse.SerializeToString,
            ),
            'AddMany': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMany,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.AddManyRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.AddManyResponse.SerializeToString,
            ),
            'RemoveMany': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMany,
                    request_deserializer=kb_dot_contract_dot_kb__pb2.RemoveManyRequest.FromString,
                    response_serializer=kb_dot_contract_dot_kb__pb2.RemoveManyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kb.v1.Kb', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kb.v1.Kb', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kb:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Init',
            kb_dot_contract_dot_kb__pb2.InitRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Create',
            kb_dot_contract_dot_kb__pb2.CreateRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Read',
            kb_dot_contract_dot_kb__pb2.ReadRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Validate',
            kb_dot_contract_dot_kb__pb2.ValidateRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Replace',
            kb_dot_contract_dot_kb__pb2.ReplaceRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.ReplaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Journal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Journal',
            kb_dot_contract_dot_kb__pb2.JournalRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.JournalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Search',
            kb_dot_contract_dot_kb__pb2.SearchRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Refs',
            kb_dot_contract_dot_kb__pb2.RefsRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.RefsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/List',
            kb_dot_contract_dot_kb__pb2.ListRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Snapshot',
            kb_dot_contract_dot_kb__pb2.SnapshotRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Add',
            kb_dot_contract_dot_kb__pb2.AddRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/Remove',
            kb_dot_contract_dot_kb__pb2.RemoveRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.RemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/CreateMany',
            kb_dot_contract_dot_kb__pb2.CreateManyRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.CreateManyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/ReplaceMany',
            kb_dot_contract_dot_kb__pb2.ReplaceManyRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.ReplaceManyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/AddMany',
            kb_dot_contract_dot_kb__pb2.AddManyRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.AddManyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kb.v1.Kb/RemoveMany',
            kb_dot_contract_dot_kb__pb2.RemoveManyRequest.SerializeToString,
            kb_dot_contract_dot_kb__pb2.RemoveManyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
